apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          image: elygo/109-pong-ingress
          ports:
            - containerPort: 8090
          env:
            - name: PORT
              value: "8090"