apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dwk-material-ingress
spec:
  rules:
    - host:
        paths:
          - path: /pong
            pathType: Prefix
            backend:
              service:
                name: pong
                port:
                  number: 2345
          - path: /status
            pathType: Prefix
            backend:
                service:
                  name: scheduler
                  port:
                    number: 2345